name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted   # must run on YOUR runner

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./artifact

      - name: Extract artifact
        run: unzip ./artifact/build.zip -d ./app

      - name: Set environment variables
        run: |
          export NODE_ENV=production
          export PORT=3000
          echo "Environment variables set!"

      - name: Run application
        run: |
          cd app
          nohup node dist/src/index.js > app.log 2>&1 &
          echo "App started on port 3000"
